#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class PodfileManager {
  constructor() {
    this.projectPath = process.cwd();
    this.podfilePath = path.join(this.projectPath, 'Podfile');
    this.configPath = path.join(this.projectPath, '.podfile-flags.json');
    this.xcodeProjectPath = path.join(this.projectPath, 'ObjRCA.xcodeproj', 'project.pbxproj');
  }

  loadConfig() {
    if (fs.existsSync(this.configPath)) {
      return JSON.parse(fs.readFileSync(this.configPath, 'utf8'));
    }
    return {
      flags: {},
      target: 'ObjRCA',
      platform: 'ios',
      version: '12.0'
    };
  }

  saveConfig(config) {
    fs.writeFileSync(this.configPath, JSON.stringify(config, null, 2));
  }

  generatePodfile(config) {
    const flags = config.flags || {};
    const enabledFlags = Object.keys(flags).filter(key => flags[key]);
    
    let podfileContent = `# Generated by podfile-manager - Preprocessor flags only
platform :${config.platform}, '${config.version}'

target '${config.target}' do
  # No pods required - just demonstrating preprocessor flags
  
  # Preprocessor flag configuration
  post_install do |installer|
    # We'll modify the main target directly via Ruby script
    require 'xcodeproj'
    
    project_path = '${this.projectPath}/ObjRCA.xcodeproj'
    project = Xcodeproj::Project.open(project_path)
    
    # Find the main target
    main_target = project.targets.find { |target| target.name == '${config.target}' }
    
    if main_target
      main_target.build_configurations.each do |config|
`;

    if (enabledFlags.length > 0) {
      const flagDefinitions = enabledFlags.map(flag => `${flag}=1`).join(' ');
      podfileContent += `        # Set preprocessor definitions for Objective-C\n`;
      podfileContent += `        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']\n`;
      podfileContent += `        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '${flagDefinitions}'\n`;
      podfileContent += `        \n`;
      podfileContent += `        # Set compilation conditions for Swift\n`;
      podfileContent += `        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= ['$(inherited)']\n`;
      podfileContent += `        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << '${enabledFlags.join(' ')}'\n`;
    } else {
      podfileContent += `        # No flags enabled - using default settings\n`;
    }
    
    podfileContent += `      end\n`;
    podfileContent += `      project.save\n`;
    podfileContent += `      puts "✅ Updated main target '${config.target}' with preprocessor flags"\n`;
    podfileContent += `    else\n`;
    podfileContent += `      puts "❌ Could not find target '${config.target}'"\n`;
    podfileContent += `    end\n`;
    podfileContent += `  end\n`;
    podfileContent += `end\n`;

    return podfileContent;
  }

  // Alternative method: Direct Xcode project modification
  modifyXcodeProjectDirectly(config) {
    const flags = config.flags || {};
    const enabledFlags = Object.keys(flags).filter(key => flags[key]);
    
    console.log('🔧 Directly modifying Xcode project build settings...');
    
    // Create a Ruby script to modify the Xcode project
    const rubyScript = `
require 'xcodeproj'

project_path = '${this.projectPath}/ObjRCA.xcodeproj'
project = Xcodeproj::Project.open(project_path)

# Find the main target
main_target = project.targets.find { |target| target.name == '${config.target}' }

if main_target
  main_target.build_configurations.each do |config|
    puts "📝 Updating configuration: #{config.name}"
    
    # Initialize preprocessor definitions if not exists
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
    config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= ['$(inherited)']
    
    # Remove any existing flag definitions
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].reject! { |def| def.match?(/^(${enabledFlags.join('|')})=/) }
    config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'].reject! { |cond| ['${enabledFlags.join("', '")}'].include?(cond) }
    
    ${enabledFlags.length > 0 ? `
    # Add new flag definitions
    ${enabledFlags.map(flag => `config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '${flag}=1'`).join('\n    ')}
    ${enabledFlags.map(flag => `config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << '${flag}'`).join('\n    ')}
    
    puts "✅ Added flags: ${enabledFlags.join(', ')}"
    ` : `
    puts "📭 No flags to add"
    `}
  end
  
  project.save
  puts "💾 Saved project file"
else
  puts "❌ Could not find target '${config.target}'"
  exit 1
end
`;

    // Write and execute the Ruby script
    const scriptPath = path.join(this.projectPath, 'temp_modify_project.rb');
    fs.writeFileSync(scriptPath, rubyScript);
    
    try {
      execSync(`ruby ${scriptPath}`, { stdio: 'inherit', cwd: this.projectPath });
      fs.unlinkSync(scriptPath); // Clean up
      return true;
    } catch (error) {
      console.error('❌ Failed to modify Xcode project:', error.message);
      if (fs.existsSync(scriptPath)) fs.unlinkSync(scriptPath);
      return false;
    }
  }

  setFlag(flagName, enabled) {
    const config = this.loadConfig();
    config.flags[flagName] = enabled;
    this.saveConfig(config);
    
    const podfileContent = this.generatePodfile(config);
    fs.writeFileSync(this.podfilePath, podfileContent);
    
    console.log(`✅ Flag '${flagName}' ${enabled ? 'enabled' : 'disabled'}`);
    console.log(`📝 Podfile updated with preprocessor flags`);
    
    // Try to modify Xcode project directly
    if (this.modifyXcodeProjectDirectly(config)) {
      console.log('🎯 Xcode project updated directly with flags!');
    } else {
      console.log('⚠️ Direct modification failed, trying pod install...');
      this.installPods();
    }
  }

  installPods() {
    console.log('📦 Configuring project with pod install...');
    try {
      execSync('pod install', { stdio: 'inherit', cwd: this.projectPath });
      console.log('✅ Project configured successfully');
    } catch (error) {
      console.error('❌ Failed to configure project:', error.message);
    }
  }

  verifyFlags() {
    console.log('🔍 Verifying current build settings...');
    try {
      const result = execSync(
        'xcrun xcodebuild -workspace ObjRCA.xcworkspace -scheme ObjRCA -showBuildSettings | grep -E "(GCC_PREPROCESSOR|SWIFT_ACTIVE)"',
        { cwd: this.projectPath, encoding: 'utf8' }
      );
      console.log('\n📋 Current Build Settings:');
      console.log('========================');
      console.log(result);
    } catch (error) {
      console.error('❌ Failed to verify build settings:', error.message);
    }
  }

  status() {
    const config = this.loadConfig();
    console.log('\n📋 Current Configuration:');
    console.log('========================');
    console.log(`Target: ${config.target}`);
    console.log(`Platform: ${config.platform} ${config.version}`);
    console.log('\n🏁 Preprocessor Flags:');
    
    if (Object.keys(config.flags).length === 0) {
      console.log('  No flags set');
    } else {
      Object.entries(config.flags).forEach(([flag, enabled]) => {
        console.log(`  ${flag}: ${enabled ? '✅ enabled' : '❌ disabled'}`);
      });
    }
    
    console.log('\n📦 Pod Dependencies: None (flags only mode)');
    console.log('💡 This setup directly modifies Xcode project build settings.');
  }

  help() {
    console.log(`
🛠️  Podfile Manager CLI - Direct Xcode Project Modification

Usage: node podfile-manager.js <command> [options]

Commands:
  enable <flag>    Enable a preprocessor flag (e.g., Turbo)
  disable <flag>   Disable a preprocessor flag
  status          Show current configuration
  verify          Verify current build settings
  install         Run pod install (fallback method)
  help            Show this help message

Examples:
  node podfile-manager.js enable Turbo
  node podfile-manager.js disable Turbo
  node podfile-manager.js status
  node podfile-manager.js verify

After enabling flags, you can use them in your code:
  Objective-C: #if Turbo
  Swift: #if Turbo

Note: This setup directly modifies your Xcode project file.
    `);
  }
}

// CLI Interface
const manager = new PodfileManager();
const [,, command, ...args] = process.argv;

switch (command) {
  case 'enable':
    if (!args[0]) {
      console.error('❌ Please specify a flag name');
      process.exit(1);
    }
    manager.setFlag(args[0], true);
    break;
    
  case 'disable':
    if (!args[0]) {
      console.error('❌ Please specify a flag name');
      process.exit(1);
    }
    manager.setFlag(args[0], false);
    break;
    
  case 'status':
    manager.status();
    break;
    
  case 'verify':
    manager.verifyFlags();
    break;
    
  case 'install':
    manager.installPods();
    break;
    
  case 'help':
  case '--help':
  case '-h':
    manager.help();
    break;
    
  default:
    if (command) {
      console.error(`❌ Unknown command: ${command}`);
    }
    manager.help();
    process.exit(1);
} 